### ISSUE TITLE
Have finished?

### ISSUE THREAD

**Issue by gzrjzcx** [Aniluj/Tower-Bloxx#1]
Hi,
Have u  finished this tower bloxx game?
I am trying to make this game by Unity, and can I get your project as the example?

Cheers
Alex

**Comment by Aniluj** [comment]
> Hi,
> Have u finished this tower bloxx game?
> I am trying to make this game by Unity, and can I get your project as the example?
> 
> Cheers
> Alex

Hi Alex, sorry for not answering before, I didn't get any notification and I saw this today by chance.
I didn't finish it because the goal of the project was to make a quick practice trying to emulate in a short period of time the mechanics of Tower Bloxx. Sorry for not being of help.

Regards.
